### ISSUE TITLE
Bug: v1.9 AlgorandVisualStudio - right clicking in a non-C# project causes a crash

### ISSUE THREAD

**Issue by mangoplane** [FrankSzendzielarz/AlgorandVisualStudio#18]
Hey!

First of all thanks for this tool and your work so far in supporting its development.

As the title says, when I right click in the window of .h files the editor immediately crashes. I suspect a few things:

(1) It carries over to all non C# files,
(2) It is caused by some interaction between the "Generate Proxy" option of your tool, and the non-C# file.

To fix this, is it possible you can completely disable the option on all non .cs files, and even add some basic Regex or semantic check to test if it's also an AlgorandVisualStudio project? Probably some assumption has been made that doesn't hold for most files like .h.

Kind regards.

**Comment by FrankSzendzielarz** [comment]
Thanks, yes. This resurfaced recently. I thought I had it squashed. Will tackle it with some urgency as it's super annoying. Thanks again.

**Comment by FrankSzendzielarz** [comment]
Should be fixed now in 1.10. Thanks again!
