### ISSUE TITLE
Production Ready Timeline - How long before this tool is production ready?

### ISSUE THREAD

**Issue by mangoplane** [FrankSzendzielarz/AlgorandVisualStudio#24]
I'm curious as to how long before your tooling is production ready. In the README it says:

> DISCLAIMER: DO NOT USE THIS VERSION FOR PRODUCTION CODE. WE ARE NOT LIABLE FOR ANYTHING.

Granted that was a few months ago, so I think it might be okay for production use?

Coming along nicely by the way.

Kind regards.

**Comment by FrankSzendzielarz** [comment]
Still in progress.
