### ISSUE TITLE
Byte[] ToTealUlong Implementation

### ISSUE THREAD

**Issue by mangoplane** [FrankSzendzielarz/AlgorandVisualStudio#26]
Hi,

The following aren't defined, making it impossible to convert to ulong from byte[], or even from string to ulong.

`Byte[] ToTealUlong`
- https://github.com/FrankSzendzielarz/AlgorandVisualStudio/blob/main/ContractDevelopment/PredefinedFunctions.md

There's no method to convert a byte string to a number either.

This change should be compliant with ARC4 ABI, which is just a specification for how to handle methods, more complex types and so forth. In PyTeal, it's just `btoi`.
- https://pyteal.readthedocs.io/en/stable/api.html#pyteal.Btoi
- https://arc.algorand.foundation/ARCs/arc-0004

So you could implement this as a simple text-replacement for ToTealUlong with the opcode btoi.  It seems very important to have simple casting of types available.

For now, I will work around it by simply including the arguments pre-expanded instead of being byte-packed into a single array. I imagine there'll be a scenario where it's not possible.

Kind regards.

**Comment by FrankSzendzielarz** [comment]
These are actually defined. Are you sure the nuget package is the latest?

**Comment by FrankSzendzielarz** [comment]
Hi again, not the VSIX but thr Nuget Packages under Dependencies / Packages in the Solution Explorer. The VSIX is out of phase with the compiler NuGet (AlgoStudio)
