### ISSUE TITLE
Add Sandbox class to automatically use account and mnemonic

### ISSUE THREAD

**Issue by rfustino** [FrankSzendzielarz/AlgorandVisualStudio#8]
Have the code default to use kmd to retrieve an account address and the mnemonic in private/dev networks. Similar to Beaker, https://github.com/algorand-devrel/beaker/blob/master/beaker/sandbox/kmd.py . This will be one less thing the user needs to do to get this to run out of the box... And if you are able to install/start sandbox automatically with the extension install,  as discussed on another issue,  this will be very close to one click setup.

**Comment by FrankSzendzielarz** [comment]
Good idea. Might add this as a utility class to net sdk and update all the adk examples too
