### ISSUE TITLE
Integrate WalleConnect for Maui solution

### ISSUE THREAD

**Issue by rfustino** [FrankSzendzielarz/AlgorandVisualStudio#9]
If TestNet/MainNet node, use the Pera Wallet to get the account. Line 45 MainPage.xml.cs. If Sandbox Private/Dev use the sandbox class to derive Account via KMD as documented in Issue 8 (https://github.com/FrankSzendzielarz/AlgorandVisualStudio/issues/8)

**Comment by FrankSzendzielarz** [comment]
WalletConnect will be part of .net sdk or walletconnectsharp. Examples using walletconnect will be provided there. Dedicated templates for WalletConnect could be added to the AlgoStudio roadmap but should be separate template items.
